name: nikkei_forecast
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  derry: ^1.4.3
  dio: ^4.0.6
  http: ^0.13.5
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_riverpod: ^2.1.1
  riverpod: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  json_serializable: ^6.5.4
freezed:
flutter:
  uses-material-design: true